def txt():
	pen.up()
	pen.setpos(-600,95)
	pen.down()
	pen.color('deep pink')
	pen.write('❤️ ❤️ ❤️ Hey My Favourite Girl ❤️ ❤️ ❤️', font=("Courier",15,"italic"))
	time.sleep(1.5)

	pen.up()
	pen.setpos(-600,60)
	pen.down()
	pen.color('red')
	pen.write("I made this small program just for you.",font=("Courier",15,"italic"))
	time.sleep(1.5)

	pen.up()
	pen.setpos(-600,25)
	pen.down()
	pen.color('red')
	pen.write("Because sometimes words feel easier through a little code.",font=("Courier",15,"italic"))
	time.sleep(2)

	pen.up()
	pen.setpos(-600,-10)
	pen.down()
	pen.color('#992600')
	pen.write("Hey my favourite girl, I just want to say I'm truly sorry.",font=("Courier",18,"italic"))
	time.sleep(2.5)

	pen.up() 
	pen.setpos(-600,-45) 
	pen.down()
	pen.color('deep pink') 
	pen.write("If I hurt you or made you feel bad, that was never my intention.", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-75) 
	pen.down() 
	pen.color('deep pink') 
	pen.write("You are someone very special, and your feelings really matter to me.", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-105) 
	pen.down() 
	pen.color('deep pink') 
	pen.write("Your smile, your kindness, and the way you are…", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-135) 
	pen.down() 
	pen.color('deep pink') 
	pen.write("Those are things I truly appreciate more than I say.", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-165) 
	pen.down() 
	pen.color('deep pink') 
	pen.write("If today is a hard day for you, I hope this small surprise helps a little.", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-195) 
	pen.down() 
	pen.color('deep pink') 
	pen.write("So I added a flower here, because I know you love tulips 🌷", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-225) 
	pen.down() 
	pen.color('deep pink') 
	pen.write("Imagine this tulip as a small reminder that someone cares about you.", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-255) 
	pen.down() 
	pen.color('deep pink') 
	pen.write("You deserve kindness, happiness, and many beautiful moments.", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-285) 
	pen.down() 
	pen.color('deep pink') 
	pen.write("And even if you're upset right now, I still hope you smile again soon.", font=("Courier", 15, "italic"))
	time.sleep(2)

	pen.up() 
	pen.setpos(-600,-315) 
	pen.down() 
	pen.color('red') 
	pen.write("This little code and tulip 🌷 are just for you, my favourite girl.", font=("Courier", 15, "italic"))
	time.sleep(2)
